### ISSUE TITLE
Html crap

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [l1ttleO/ProjectFNF#49]
### Describe your problem here.

So idk if this on normal oject fnf or not but when i ported the source to html it just psych engine not project fnf i was just wondering if that has to be fixed it or it dosent work on html

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope i havent edited anything i just ported it

**Comment by l1ttleO** [comment]
You did not apply patches before compiling
Use the `art/apply-existing-patches.bat`
The README instructions will be updated soon

**Comment by LEVIXDDLMAO** [comment]
one more thing how would i get this to work on actions?

**Comment by l1ttleO** [comment]
Insert
```yml
      - name: Apply patches
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          cp -r patches/assets .
          git am patches/source/*.patch
        shell: bash
``` 
right before the Compile step.
You should end up with something like this:
```yml
      - name: Apply patches
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          cp -r patches/assets .
          git am patches/source/*.patch
        shell: bash
      - name: Compile
        run: haxelib run lime build Project.xml html5 --app-version="4.0.0-${{ github.run_id}}"
```
